### ISSUE TITLE
Not able to install the tool after it has been updated

### ISSUE THREAD

**Issue by MirnaAlaisami** [overview/overview-local#27] opened 2020-05-04 08:46 UTC
Installing and using the tool was working fine last week, however today it gives the following error when trying to install/start:
```
Pulling overview-database (overview/overview-database:8e21682e5980d329f8778b2f790c5b252dd186db)...
manifest for overview/overview-database:8e21682e5980d329f8778b2f790c5b252dd186db not found: manifest unknown: manifest unknown
Command failed with error 1

```
I can see that there were some updates done 3 days ago, so I guess something went wrong after that.

**Comment by adamhooper** [comment] 2020-05-04 14:26
@MirnaAlaisami Thanks for the report! It looks like our build system didn't upload a new version of Overview correctly. I'll fix this right away.

**Comment by adamhooper** [comment] 2020-05-04 14:54
@MirnaAlaisami I've pushed a fix, so you can keep using overview-local.

(Technical mumbo-jumbo: the problem is, Jenkins didn't push the version of Overview that was needed. Local testing of `overview-local` doesn't catch this because Docker images are tagged on the dev machine prior to push. My short-term solution is to revert to a _published_ version of Overview, from before the Jenkinsfile error. I'll mark this issue resolved when I fix Jenkins to upload new versions.)

**Comment by MirnaAlaisami** [comment] 2020-05-04 15:01
@adamhooper Perfect, thanks for the explanation.

**Comment by adamhooper** [comment] 2020-05-05 21:35
Jenkins fixed!

**Closed by adamhooper** 2020-05-05 21:35 UTC
